// <auto-generated />
namespace TestEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Role_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201809091728276_Role_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
