// <auto-generated />
namespace TestEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TestDBv2createImageM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestDBv2createImageM));
        
        string IMigrationMetadata.Id
        {
            get { return "201809011655384_TestDB-v2-createImageM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
