// <auto-generated />
namespace TestEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class role_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(role_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201809121600036_role_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
